package com.eayun.virtualization.model;

// Generated 2015-8-24 11:09:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang3.StringUtils;

import com.eayun.eayunstack.model.Hypervisor;



/**
 * CloudComputenode generated by hbm2java
 */
@Entity
@Table(name = "cloud_computenode")
public class BaseCloudComputenode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String id;
	private String hostId;
	private String dcId;
	private String hostName;
	private String hostIp;
	private BigDecimal runningVms;
	private BigDecimal vcpus;
	private BigDecimal vcpuUsed;
	private BigDecimal memoryMb;
	private BigDecimal memoryUsed;
	private BigDecimal freeDisk;
	private BigDecimal freeRam;
	private String hostStatus;
	private String serverOutnet;
	private String reserve1;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;

	public BaseCloudComputenode() {
	}

	public BaseCloudComputenode(String hostId) {
		this.hostId = hostId;
	}

	public BaseCloudComputenode(String id,String hostId, String dcId, String hostName,
			String hostIp, BigDecimal runningVms, BigDecimal vcpus,
			BigDecimal vcpuUsed, BigDecimal memoryMb, BigDecimal memoryUsed,
			BigDecimal freeDisk, BigDecimal freeRam, String hostStatus,
			String serverOutnet, String reserve1, String reserve2,
			String reserve3, String reserve4, String reserve5) {
		this.id=id;
		this.hostId = hostId;
		this.dcId = dcId;
		this.hostName = hostName;
		this.hostIp = hostIp;
		this.runningVms = runningVms;
		this.vcpus = vcpus;
		this.vcpuUsed = vcpuUsed;
		this.memoryMb = memoryMb;
		this.memoryUsed = memoryUsed;
		this.freeDisk = freeDisk;
		this.freeRam = freeRam;
		this.hostStatus = hostStatus;
		this.serverOutnet = serverOutnet;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.reserve4 = reserve4;
		this.reserve5 = reserve5;
	}
	
	public BaseCloudComputenode(Hypervisor hyper,String dcId){
		if(null!=hyper){
			this.hostId = hyper.getId();
			this.dcId = dcId;
			this.hostName = hyper.getHypervisor_hostname();
			this.hostIp = hyper.getHost_ip();
			this.hostStatus = hyper.getStatus()!=null?hyper.getStatus().toUpperCase():"";
			if(!StringUtils.isEmpty(hyper.getRunning_vms()))
				this.runningVms = new BigDecimal(hyper.getRunning_vms());
			if(!StringUtils.isEmpty(hyper.getVcpus()))
				this.vcpus = new BigDecimal(hyper.getVcpus());
			if(!StringUtils.isEmpty(hyper.getVcpus_used()))
				this.vcpuUsed = new BigDecimal(hyper.getVcpus_used());
			if(!StringUtils.isEmpty(hyper.getMemory_mb()))
				this.memoryMb = new BigDecimal(hyper.getMemory_mb());
			if(!StringUtils.isEmpty(hyper.getMemory_mb_used()))
				this.memoryUsed = new BigDecimal(hyper.getMemory_mb_used());
			if(!StringUtils.isEmpty(hyper.getFree_disk_gb()))
				this.freeDisk = new BigDecimal(hyper.getFree_disk_gb());
			if(!StringUtils.isEmpty(hyper.getFree_ram_mb()))
				this.freeRam = new BigDecimal(hyper.getFree_ram_mb());
		}
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}
	
	public void setId(String id){
		this.id=id;
	}
	
	@Column(name = "host_id", length = 100)
	public String getHostId() {
		return this.hostId;
	}

	public void setHostId(String hostId) {
		this.hostId = hostId;
	}

	@Column(name = "dc_id", length = 100)
	public String getDcId() {
		return this.dcId;
	}

	public void setDcId(String dcId) {
		this.dcId = dcId;
	}

	@Column(name = "host_name", length = 100)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "host_ip", length = 100)
	public String getHostIp() {
		return this.hostIp;
	}

	public void setHostIp(String hostIp) {
		this.hostIp = hostIp;
	}

	@Column(name = "running_vms", precision = 20, scale = 0)
	public BigDecimal getRunningVms() {
		return this.runningVms;
	}

	public void setRunningVms(BigDecimal runningVms) {
		this.runningVms = runningVms;
	}

	@Column(name = "vcpus", precision = 20, scale = 0)
	public BigDecimal getVcpus() {
		return this.vcpus;
	}

	public void setVcpus(BigDecimal vcpus) {
		this.vcpus = vcpus;
	}

	@Column(name = "vcpu_used", precision = 20, scale = 0)
	public BigDecimal getVcpuUsed() {
		return this.vcpuUsed;
	}

	public void setVcpuUsed(BigDecimal vcpuUsed) {
		this.vcpuUsed = vcpuUsed;
	}

	@Column(name = "memory_mb", precision = 20, scale = 0)
	public BigDecimal getMemoryMb() {
		return this.memoryMb;
	}

	public void setMemoryMb(BigDecimal memoryMb) {
		this.memoryMb = memoryMb;
	}

	@Column(name = "memory_used", precision = 20, scale = 0)
	public BigDecimal getMemoryUsed() {
		return this.memoryUsed;
	}

	public void setMemoryUsed(BigDecimal memoryUsed) {
		this.memoryUsed = memoryUsed;
	}

	@Column(name = "free_disk", precision = 20, scale = 0)
	public BigDecimal getFreeDisk() {
		return this.freeDisk;
	}

	public void setFreeDisk(BigDecimal freeDisk) {
		this.freeDisk = freeDisk;
	}

	@Column(name = "free_ram", precision = 20, scale = 0)
	public BigDecimal getFreeRam() {
		return this.freeRam;
	}

	public void setFreeRam(BigDecimal freeRam) {
		this.freeRam = freeRam;
	}

	@Column(name = "host_status", length = 50)
	public String getHostStatus() {
		return this.hostStatus;
	}

	public void setHostStatus(String hostStatus) {
		this.hostStatus = hostStatus;
	}

	@Column(name = "server_outnet", length = 100)
	public String getServerOutnet() {
		return this.serverOutnet;
	}

	public void setServerOutnet(String serverOutnet) {
		this.serverOutnet = serverOutnet;
	}

	@Column(name = "reserve1", length = 100)
	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 100)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@Column(name = "reserve3", length = 100)
	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	@Column(name = "reserve4", length = 100)
	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	@Column(name = "reserve5", length = 100)
	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

}
