package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysSelfuserprj generated by hbm2java
 * 用户-项目关联表
 */
@Entity
@Table(name = "sys_selfuserprj")
public class BaseUserPrj implements java.io.Serializable {
	
	private static final long serialVersionUID = -9103300995055026952L;
	
	private String userprjId;      //id
	private String projectId;      //项目id
	private String userId;         //账号id
	private String userprjDesc;    //描述
	private Integer userprjSort;   //排序

	public BaseUserPrj() {
	}

	public BaseUserPrj(String userprjId) {
		this.userprjId = userprjId;
	}
	@Id
	@GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "userprj_id", unique = true, nullable = false, length = 32)
	public String getUserprjId() {
		return this.userprjId;
	}

	public void setUserprjId(String userprjId) {
		this.userprjId = userprjId;
	}

	@Column(name = "project_id", length = 32)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "userprj_desc", length = 500)
	public String getUserprjDesc() {
		return this.userprjDesc;
	}

	public void setUserprjDesc(String userprjDesc) {
		this.userprjDesc = userprjDesc;
	}

	@Column(name = "userprj_sort", precision = 10, scale = 0)
	public Integer getUserprjSort() {
		return userprjSort;
	}

	public void setUserprjSort(Integer userprjSort) {
		this.userprjSort = userprjSort;
	}

}
