package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysSelfrole generated by hbm2java
 * 角色
 */
@Entity
@Table(name = "sys_selfrole")
public class BaseRole implements java.io.Serializable {

	private static final long serialVersionUID = 5230948207891122076L;
	private String roleId;             //角色id
	private String roleName;           //角色名称
	private String roleDesc;           //角色描述
	private Character roleValid ='0';  //是否有效
	private String cusId;              //所属客户

	public BaseRole() {
	}

	public BaseRole(String roleId) {
		this.roleId = roleId;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "role_id", unique = true, nullable = false, length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc", length = 500)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Column(name = "role_valid", length = 1)
	public Character getRoleValid() {
		return this.roleValid;
	}

	public void setRoleValid(Character roleValid) {
		this.roleValid = roleValid;
	}

	@Column(name = "cus_id", length = 32)
	public String getCusId() {
		return this.cusId;
	}

	public void setCusId(String cusId) {
		this.cusId = cusId;
	}

}
