package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysSelfuser generated by hbm2java
 * 用户表-登录的人的层面
 */
@Entity
@Table(name = "sys_selfuser")
public class BaseUser implements java.io.Serializable {

	private static final long serialVersionUID = -5965434805511146946L;
	private String userId;         //账号id
	private String userAccount;    //账号
	private String userPassword;   //密码
	private String salt;           //密码盐
	private String userPerson;     //用户姓名
	private String userPhone;      //电话
	private String userEmail;      //邮件
	private String cusId;          //所属客户id
	private Character userSex;     //性别
	private Date lastTime;         //最后修改时间(上次登录时间，为null时表示首次登录)
	private String roleId;         //角色id
	private Date createTime;       //创建时间
	private String userExplain;    //账号说明
	private Boolean isMailValid;   //邮箱是否验证
	private Boolean isPhoneValid;  //手机是否验证
	private Boolean isAdmin;       //是否是超级管理员
	private Boolean isBlocked;//是否被冻结

	
	public BaseUser() {
	}
	
	public BaseUser(String userId, String userAccount, String userPhone, String userEmail, Boolean isMailValid, Boolean isPhoneValid) {
		this.userId = userId;
		this.userAccount = userAccount;
		this.userPhone = userPhone;
		this.userEmail = userEmail;
		this.isMailValid = isMailValid;
		this.isPhoneValid = isPhoneValid;
	}
	@Id
	@GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "user_id", unique = true, nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_account", length = 32)
	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	@Column(name = "user_password", length = 32)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_person", length = 100)
	public String getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(String userPerson) {
		this.userPerson = userPerson;
	}

	@Column(name = "user_phone", length = 32)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_email", length = 100)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "cus_id", length = 32)
	public String getCusId() {
		return this.cusId;
	}

	public void setCusId(String cusId) {
		this.cusId = cusId;
	}

	@Column(name = "user_sex", length = 1)
	public Character getUserSex() {
		return this.userSex;
	}

	public void setUserSex(Character userSex) {
		this.userSex = userSex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_time" , length = 19)
	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "user_explain", length = 400)
	public String getUserExplain() {
		return this.userExplain;
	}

	public void setUserExplain(String userExplain) {
		this.userExplain = userExplain;
	}

	@Column(name = "user_isemailvalid")
    public Boolean getIsMailValid() {
        return isMailValid;
    }

    public void setIsMailValid(Boolean isMailValid) {
        this.isMailValid = isMailValid;
    }

    @Column(name = "user_isphonevalid")
    public Boolean getIsPhoneValid() {
        return isPhoneValid;
    }

    public void setIsPhoneValid(Boolean isPhoneValid) {
        this.isPhoneValid = isPhoneValid;
    }
    @Column(name = "is_admin")
    public Boolean getIsAdmin() {
        return isAdmin;
    }
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    @Column(name = "salt",length = 20)
    public String getSalt() {
        return salt;
    }
    public void setSalt(String salt) {
        this.salt = salt;
    }
    @Column(name = "is_blocked")
	public Boolean getIsBlocked() {
		return isBlocked;
	}

	public void setIsBlocked(Boolean isBlocked) {
		this.isBlocked = isBlocked;
	}

}
