package com.eayun.customer.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysSelfpower generated by hbm2java
 * 模块（权限）
 */
@Entity
@Table(name = "sys_selfpower")
public class BasePower implements java.io.Serializable {

    private static final long serialVersionUID = -4265219814176726621L;
    private String            powerId;                                 //权限id
    private String            powerName;                               //权限名称
    private String            powerUrl;                                //权限url
    private String            powerRoute;                              //权限标识
    private Integer           powerSort;                               //权限排序
    private String            parentId;                                //父类id
    private String            powerDesc;                               //权限描述
    private String            powerIcon;                               //图标

    public BasePower() {
    }

    public BasePower(String powerId) {
        this.powerId = powerId;
    }

    @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid")
    @Column(name = "power_id", unique = true, nullable = false, length = 32)
    public String getPowerId() {
        return this.powerId;
    }

    public void setPowerId(String powerId) {
        this.powerId = powerId;
    }

    @Column(name = "power_name", length = 100)
    public String getPowerName() {
        return this.powerName;
    }

    public void setPowerName(String powerName) {
        this.powerName = powerName;
    }

    @Column(name = "power_url", length = 100)
    public String getPowerUrl() {
        return this.powerUrl;
    }

    public void setPowerUrl(String powerUrl) {
        this.powerUrl = powerUrl;
    }

    @Column(name = "power_route", length = 200)
    public String getPowerRoute() {
        return this.powerRoute;
    }

    public void setPowerRoute(String powerRoute) {
        this.powerRoute = powerRoute;
    }

    @Column(name = "power_sort")
    public Integer getPowerSort() {
        return powerSort;
    }

    public void setPowerSort(Integer powerSort) {
        this.powerSort = powerSort;
    }

    @Column(name = "parent_id", length = 32)
    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    @Column(name = "power_desc", length = 500)
    public String getPowerDesc() {
        return this.powerDesc;
    }

    public void setPowerDesc(String powerDesc) {
        this.powerDesc = powerDesc;
    }

    @Column(name = "power_icon", length = 100)
    public String getPowerIcon() {
        return powerIcon;
    }

    public void setPowerIcon(String powerIcon) {
        this.powerIcon = powerIcon;
    }

}
