package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysSelfrolepower generated by hbm2java
 * 角色权限
 */
@Entity
@Table(name = "sys_selfrolepower")
public class BaseRolePower implements java.io.Serializable {

	private static final long serialVersionUID = 4622916450009162181L;
	
	private String rpId;       //角色权限id
	private String roleId;     //角色id
	private String powerId;    //权限id
	private String rpDesc;     //描述
	private Integer rpSort;    //排序
	private Character rpState='1';//状态  0无效1.有效

	public BaseRolePower() {
	}

	public BaseRolePower(String rpId) {
		this.rpId = rpId;
	}
	@Id
	@GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "rp_id", unique = true, nullable = false, length = 32)
	public String getRpId() {
		return this.rpId;
	}

	public void setRpId(String rpId) {
		this.rpId = rpId;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "power_id", length = 32)
	public String getPowerId() {
		return this.powerId;
	}

	public void setPowerId(String powerId) {
		this.powerId = powerId;
	}

	@Column(name = "rp_desc", length = 500)
	public String getRpDesc() {
		return this.rpDesc;
	}

	public void setRpDesc(String rpDesc) {
		this.rpDesc = rpDesc;
	}

	@Column(name = "rp_sort")
	public Integer getRpSort() {
		return rpSort;
	}
	
	public void setRpSort(Integer rpSort) {
		this.rpSort = rpSort;
	}
	
	@Column(name = "rp_state", length = 1)
	public Character getRpState() {
		return this.rpState;
	}

	public void setRpState(Character rpState) {
		this.rpState = rpState;
	}

}
