package com.eayun.customer.model;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * SysSelfcustomer generated by hbm2java
 * 客户-公司层面
 */
@Entity
@Table(name = "cus_blockresource")
public class CusBlockResource implements java.io.Serializable{

	private static final long serialVersionUID = -5894892224658784684L;
	
	
	private String blockId;        //主键 随机数
	private String cusId;          //客户id
	private Boolean isBlocked;      //是否被冻结 1：冻结；0：解冻
	private Boolean blockopStatus;     //冻结成功与否    0：冻结失败 1：冻结成功
	private Date updateTime;         //上次更新时间
	private String blockAccount;       //记录ecmc的冻结操作记录
	private String unblockAccount;       //记录ecmc的解冻操作记录
	private String blockCloudResource;       //记录主机的冻结结果
	private String unblockCloudResource;        //记录主机解冻的结果
	
	
	@Id
	@GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "block_id", unique = true, nullable = false, length = 32)
	public String getBlockId() {
		return blockId;
	}
	public void setBlockId(String blockId) {
		this.blockId = blockId;
	}
	
	@Column(name = "cus_id", length = 32)
	public String getCusId() {
		return cusId;
	}
	public void setCusId(String cusId) {
		this.cusId = cusId;
	}
	@Column(name = "is_blocked")
	public Boolean getIsBlocked() {
		return isBlocked;
	}
	public void setIsBlocked(Boolean isBlocked) {
		this.isBlocked = isBlocked;
	}
	
	@Column(name = "block_opstatus")
	public Boolean getBlockopStatus() {
		return blockopStatus;
	}
	public void setBlockopStatus(Boolean blockopStatus) {
		this.blockopStatus = blockopStatus;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time" , length = 19)
	public Date getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	@Lob
    @Basic(fetch = FetchType.LAZY)
    @Type(type = "text")
    @Column(name = "block_account")
	public String getBlockAccount() {
		return blockAccount;
	}
	public void setBlockAccount(String blockAccount) {
		this.blockAccount = blockAccount;
	}
	@Lob
    @Basic(fetch = FetchType.LAZY)
    @Type(type = "text")
    @Column(name = "unblock_account")
	public String getUnblockAccount() {
		return unblockAccount;
	}
	public void setUnblockAccount(String unblockAccount) {
		this.unblockAccount = unblockAccount;
	}
	@Lob
    @Basic(fetch = FetchType.LAZY)
    @Type(type = "text")
    @Column(name = "block_cloudresource")
	public String getBlockCloudResource() {
		return blockCloudResource;
	}
	public void setBlockCloudResource(String blockCloudResource) {
		this.blockCloudResource = blockCloudResource;
	}
	
	@Lob
    @Basic(fetch = FetchType.LAZY)
    @Type(type = "text")
    @Column(name = "unblock_cloudresource")
	public String getUnblockCloudResource() {
		return unblockCloudResource;
	}
	public void setUnblockCloudResource(String unblockCloudResource) {
		this.unblockCloudResource = unblockCloudResource;
	}
	
	
}
