package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1



/**
 * SysSelfpower generated by hbm2java
 */
public class Power extends BasePower{

	private static final long serialVersionUID = -668538954015000103L;
	
	private String parentName;//父类名称
	
	public String getParentName() {
		return parentName;
	}
	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

}
