package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1


/**
 * SysSelfrole generated by hbm2java
 */
public class Role extends BaseRole{

	private static final long serialVersionUID = -6605802484998533762L;

	private String roleValidName;//是否有效.

	public String getRoleValidName() {
		return roleValidName;
	}

	public void setRoleValidName(String roleValidName) {
		this.roleValidName = roleValidName;
	}
	
	
}
