package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1



/**
 * SysSelfrolepower generated by hbm2java
 */
public class RolePower extends BaseRolePower {

	private static final long serialVersionUID = 3351386066770523709L;
	
	private String roleName;//角色名称
	private String powerName;//权限名称
	private String rpStateName;//状态名称
	public String getRoleName() {
		return roleName;
	}
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	public String getPowerName() {
		return powerName;
	}
	public void setPowerName(String powerName) {
		this.powerName = powerName;
	}
	public String getRpStateName() {
		return rpStateName;
	}
	public void setRpStateName(String rpStateName) {
		this.rpStateName = rpStateName;
	}
	
	
}
