package com.eayun.customer.model;

import java.util.ArrayList;
import java.util.List;

/**
 * SysSelfuser generated by hbm2java
 */
public class User extends BaseUser {

    private static final long serialVersionUID = -654049532501253141L;

    private String            cusName;                                   //商务人员名称
    private String            userSexName;                               //性别名称
    private String            roleName;                                  //角色名称
    private List<String>      projectNameList  = new ArrayList<String>();
    private int				  unreadCount;								 //未读消息数
    
    private String            cusCpname;                                 //公司中文名称

    public String getCusName() {
        return cusName;
    }

    public void setCusName(String cusName) {
        this.cusName = cusName;
    }

    public String getUserSexName() {
        return userSexName;
    }

    public void setUserSexName(String userSexName) {
        this.userSexName = userSexName;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public List<String> getProjectNameList() {
        return projectNameList;
    }

    public void setProjectNameList(List<String> projectNameList) {
        this.projectNameList = projectNameList;
    }

	public int getUnreadCount() {
		return unreadCount;
	}

	public void setUnreadCount(int unreadCount) {
		this.unreadCount = unreadCount;
	}

	public String getCusCpname() {
		return cusCpname;
	}

	public void setCusCpname(String cusCpname) {
		this.cusCpname = cusCpname;
	}
    
}
