package com.eayun.customer.model;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1


/**
 * SysSelfuserprj generated by hbm2java
 */
public class UserPrj extends BaseUserPrj{

	private static final long serialVersionUID = 4992287346826920202L;

	private String prjName;//项目名称
	private String userName;//用户名称
	
	public String getPrjName() {
		return prjName;
	}
	public void setPrjName(String prjName) {
		this.prjName = prjName;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	
}
